# ?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhihu-backend
    username: root
    password: zlpen9hth
# ????
logging:
  level:
    root: info
  file:
    path: D:\\logs\\zhihuBackend\\
# ???
server:
  port: 8081
# mybatis??
mybatis-plus:
  # xml????
  mapper-locations: mapper/*.xml
  configuration:
    #  ????
    map-underscore-to-camel-case: true
    #    ??sql??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
