
spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/zhihu-backend
    username: root
    password: en9hth

logging:
  level:
    root: info
  file:
    path: D:\\logs\\zhihuBackend\\

server:
  port: 8081

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
