package com.forzlp.zhihubackend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Transactional;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
/**
 * @author zlp
 * @date 2023/8/4 16:51
 */

@SpringBootApplication
@EnableTransactionManagement
public class ZhihuBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(ZhihuBackendApplication.class, args);
    }

}
